### ISSUE TITLE
Need to store a persistent information

### ISSUE THREAD

**Issue by ale8193** [ale8193/shamir-fido#12]
We need to integrate a way to persist one user information, the number of registered device, because when we create the new shard for authenticate a new device we must set a new id for this shard, the id can't be always the same and must be one more for each device.

There are at least tree possible solution that allow to maintain this information locally to the app:

1. store into a file inside the application
2. use browser store session
3. use [neDB](https://www.npmjs.com/package/nedb), a simple and lightweight database mongo like, written in plain javascript used for store simple information in electron application

**Comment by sabbio93** [comment]
@ale8193 no just randomize id no mem
