### ISSUE TITLE
Did mount

### ISSUE THREAD

**Issue by sabbio93** [ale8193/shamir-fido#4]
https://github.com/ale8193/shamir-fido/blob/22aee30a22a273df8cc363018a195392259ab7cd/src/App.js#L22
Come mai hai messo l'inizializzazione in didmount invece che nel constructor

**Comment by ale8193** [comment]
Inizialmente avevo intenzione di fare anche altre operazioni nel didmount ma poi ho notato che era meglio metterle nel didUpdate e quella l'ho lasciata li, alla fine non cambia nulla, però forse è più elegante toglierlo e metterlo nel costruttore

**Comment by ale8193** [comment]
In ogni caso per ho rimosso il set state nel didmount e l'ho messo nel costruttore

**Comment by sabbio93** [comment]
@ale8193 Anche il didupdate l hai tolto?

**Comment by ale8193** [comment]
No no il didupdate l'ho lasciato perchè serve
