### ISSUE TITLE
Problemi nell'encrypt e decrypt di un file

### ISSUE THREAD

**Issue by ale8193** [ale8193/shamir-fido#9]
Durante la encrypt e decrypt di un file ho i seguenti problemi:

-  aprendo uno stream in lettura non riesco a leggere le informazioni dagli eventi a meno che non uso la pipe, ma cosi facendo non riesco a leggere le informazioni e salvarle in una variabile;
- Nella decipher non viene mai invocata la end di decifratura non si sa perchè, il codice va quindi revisionato.

**Comment by sabbio93** [comment]
https://github.com/ale8193/shamir-fido/blob/3be11fd4b0773d8f1fb0dd9eab7c940182e0611a/src/utils/crypto-utils.js#L27-61
